name: 'Airflow DAGs Validation'
author: jayamanikharyono
description: 'Validate DAGs, variables and dependencies on your workflows.'
branding:
  icon: check
  color: gray-dark

inputs:
  dagPaths:
    description: 'DAG dir to validate'
    required: false
    default: "dags"
  pluginPaths:
    description: 'Plugin dir to validate'
    required: false
    default: "plugins"
  airflowVersion:
    description: 'Airflow version to be tested'
    required: false
    default: "2.2.4"
  pythonVersion:
    description: 'Python version to be installed'
    required: false
    default: "3.7"
  requirementsFile:
    description: 'Path to requirements file that airflow use to run the DAG files.'
    required: false
    default: "requirements.txt"
  varFile:
    description: 'Path to var.json file that will be used to set Variable on airflow'
    required: false
    default: ""
  connFile:
    description: 'Path to conns.json file that will be used to set Connections on airflow'
    required: false
    default: ""
  loadExamples:
    description: 'Boolean flag for whether to load example dag or not'
    required: false
    default: "False"
  accessToken:
    description: 'Repo access token'
    required: true

outputs:
  validator-result:
    description: 'DAGs validator result'
    value: ${{ steps.run.outputs }}

runs:
  using: 'composite'
  steps:
    - id: build
      run: docker build -t airflow:latest --build-arg PYTHON_VERSION=${{ inputs.pythonVersion }} --build-arg AIRFLOW_VERSION=${{ inputs.airflowVersion }} .
      shell: bash
    - id: run
      run: |
        docker run --rm -v $(pwd):/github/workspace --workdir /github/workspace airflow:latest \
          ${{ inputs.requirementsFile }} \
          ${{ inputs.dagPaths }} \
          ${{ inputs.varFile }} \
          ${{ inputs.connFile }} \
          ${{ inputs.pluginPaths }} \
          ${{ inputs.loadExamples }} \
          ${{ inputs.accessToken }} >> $GITHUB_OUTPUT
      shell: bash
